// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countAllFeeds = `-- name: CountAllFeeds :one
SELECT COUNT(*) FROM feeds
`

func (q *Queries) CountAllFeeds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllFeeds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, author_id, title, feed_url, home_url, description, poll_interval_sec)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, author_id, title, feed_url, home_url, description,
         etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
`

type CreateFeedParams struct {
	UserID          int64          `json:"user_id"`
	AuthorID        sql.NullInt64  `json:"author_id"`
	Title           string         `json:"title"`
	FeedUrl         string         `json:"feed_url"`
	HomeUrl         sql.NullString `json:"home_url"`
	Description     sql.NullString `json:"description"`
	PollIntervalSec int64          `json:"poll_interval_sec"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.UserID,
		arg.AuthorID,
		arg.Title,
		arg.FeedUrl,
		arg.HomeUrl,
		arg.Description,
		arg.PollIntervalSec,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorID,
		&i.Title,
		&i.FeedUrl,
		&i.HomeUrl,
		&i.Description,
		&i.Etag,
		&i.LastModified,
		&i.LastPolledAt,
		&i.LastError,
		&i.PollIntervalSec,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :execresult
DELETE FROM feeds
WHERE id = ? AND user_id = ?
`

type DeleteFeedParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, author_id, title, feed_url, home_url, description,
       etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
FROM feeds
WHERE id = ? AND user_id = ?
`

type GetFeedParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorID,
		&i.Title,
		&i.FeedUrl,
		&i.HomeUrl,
		&i.Description,
		&i.Etag,
		&i.LastModified,
		&i.LastPolledAt,
		&i.LastError,
		&i.PollIntervalSec,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedAny = `-- name: GetFeedAny :one
SELECT id, user_id, author_id, title, feed_url, home_url, description,
       etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
FROM feeds
WHERE id = ?
`

func (q *Queries) GetFeedAny(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedAny, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorID,
		&i.Title,
		&i.FeedUrl,
		&i.HomeUrl,
		&i.Description,
		&i.Etag,
		&i.LastModified,
		&i.LastPolledAt,
		&i.LastError,
		&i.PollIntervalSec,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedByTitle = `-- name: GetFeedByTitle :one
SELECT id, user_id, author_id, title, feed_url, home_url, description,
       etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
FROM feeds
WHERE user_id = ? AND title = ? COLLATE NOCASE
`

type GetFeedByTitleParams struct {
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) GetFeedByTitle(ctx context.Context, arg GetFeedByTitleParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByTitle, arg.UserID, arg.Title)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorID,
		&i.Title,
		&i.FeedUrl,
		&i.HomeUrl,
		&i.Description,
		&i.Etag,
		&i.LastModified,
		&i.LastPolledAt,
		&i.LastError,
		&i.PollIntervalSec,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAllFeeds = `-- name: ListAllFeeds :many
SELECT f.id, f.user_id, f.author_id, f.title, f.feed_url, f.home_url, f.description,
       f.etag, f.last_modified, f.last_polled_at, f.last_error, f.poll_interval_sec, f.enabled, f.created_at,
       u.username AS owner
FROM feeds f
JOIN users u ON u.id = f.user_id
ORDER BY u.username, f.title
`

type ListAllFeedsRow struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	AuthorID        sql.NullInt64  `json:"author_id"`
	Title           string         `json:"title"`
	FeedUrl         string         `json:"feed_url"`
	HomeUrl         sql.NullString `json:"home_url"`
	Description     sql.NullString `json:"description"`
	Etag            sql.NullString `json:"etag"`
	LastModified    sql.NullString `json:"last_modified"`
	LastPolledAt    sql.NullString `json:"last_polled_at"`
	LastError       sql.NullString `json:"last_error"`
	PollIntervalSec int64          `json:"poll_interval_sec"`
	Enabled         bool           `json:"enabled"`
	CreatedAt       string         `json:"created_at"`
	Owner           string         `json:"owner"`
}

func (q *Queries) ListAllFeeds(ctx context.Context) ([]ListAllFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllFeedsRow
	for rows.Next() {
		var i ListAllFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorID,
			&i.Title,
			&i.FeedUrl,
			&i.HomeUrl,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.LastPolledAt,
			&i.LastError,
			&i.PollIntervalSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, author_id, title, feed_url, home_url, description,
       etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
FROM feeds
WHERE user_id = ?
ORDER BY title
`

func (q *Queries) ListFeeds(ctx context.Context, userID int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorID,
			&i.Title,
			&i.FeedUrl,
			&i.HomeUrl,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.LastPolledAt,
			&i.LastError,
			&i.PollIntervalSec,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByAuthor = `-- name: ListFeedsByAuthor :many
SELECT id, user_id, author_id, title, feed_url, home_url, description,
       etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
FROM feeds
WHERE user_id = ? AND author_id = ?
ORDER BY title
`

type ListFeedsByAuthorParams struct {
	UserID   int64         `json:"user_id"`
	AuthorID sql.NullInt64 `json:"author_id"`
}

func (q *Queries) ListFeedsByAuthor(ctx context.Context, arg ListFeedsByAuthorParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByAuthor, arg.UserID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorID,
			&i.Title,
			&i.FeedUrl,
			&i.HomeUrl,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.LastPolledAt,
			&i.LastError,
			&i.PollIntervalSec,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByAuthorWithUnread = `-- name: ListFeedsByAuthorWithUnread :many
SELECT f.id, f.user_id, f.author_id, f.title, f.feed_url, f.home_url, f.description,
       f.etag, f.last_modified, f.last_polled_at, f.last_error, f.poll_interval_sec, f.enabled, f.created_at,
       a.name AS author_name,
       (SELECT COUNT(*) FROM items i WHERE i.feed_id = f.id AND i.read = 0) AS unread
FROM feeds f
LEFT JOIN authors a ON a.id = f.author_id
WHERE f.user_id = ? AND f.author_id = ?
ORDER BY f.title
`

type ListFeedsByAuthorWithUnreadParams struct {
	UserID   int64         `json:"user_id"`
	AuthorID sql.NullInt64 `json:"author_id"`
}

type ListFeedsByAuthorWithUnreadRow struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	AuthorID        sql.NullInt64  `json:"author_id"`
	Title           string         `json:"title"`
	FeedUrl         string         `json:"feed_url"`
	HomeUrl         sql.NullString `json:"home_url"`
	Description     sql.NullString `json:"description"`
	Etag            sql.NullString `json:"etag"`
	LastModified    sql.NullString `json:"last_modified"`
	LastPolledAt    sql.NullString `json:"last_polled_at"`
	LastError       sql.NullString `json:"last_error"`
	PollIntervalSec int64          `json:"poll_interval_sec"`
	Enabled         bool           `json:"enabled"`
	CreatedAt       string         `json:"created_at"`
	AuthorName      sql.NullString `json:"author_name"`
	Unread          int64          `json:"unread"`
}

func (q *Queries) ListFeedsByAuthorWithUnread(ctx context.Context, arg ListFeedsByAuthorWithUnreadParams) ([]ListFeedsByAuthorWithUnreadRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByAuthorWithUnread, arg.UserID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsByAuthorWithUnreadRow
	for rows.Next() {
		var i ListFeedsByAuthorWithUnreadRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorID,
			&i.Title,
			&i.FeedUrl,
			&i.HomeUrl,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.LastPolledAt,
			&i.LastError,
			&i.PollIntervalSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.AuthorName,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsDue = `-- name: ListFeedsDue :many
SELECT id, user_id, author_id, title, feed_url, home_url, description,
       etag, last_modified, last_polled_at, last_error, poll_interval_sec, enabled, created_at
FROM feeds
WHERE enabled = 1
  AND (last_polled_at IS NULL OR last_polled_at <= datetime(CAST(?1 AS TEXT), '-' || poll_interval_sec || ' seconds'))
`

func (q *Queries) ListFeedsDue(ctx context.Context, now string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsDue, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorID,
			&i.Title,
			&i.FeedUrl,
			&i.HomeUrl,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.LastPolledAt,
			&i.LastError,
			&i.PollIntervalSec,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsWithUnread = `-- name: ListFeedsWithUnread :many
SELECT f.id, f.user_id, f.author_id, f.title, f.feed_url, f.home_url, f.description,
       f.etag, f.last_modified, f.last_polled_at, f.last_error, f.poll_interval_sec, f.enabled, f.created_at,
       a.name AS author_name,
       (SELECT COUNT(*) FROM items i WHERE i.feed_id = f.id AND i.read = 0) AS unread
FROM feeds f
LEFT JOIN authors a ON a.id = f.author_id
WHERE f.user_id = ?
ORDER BY f.title
`

type ListFeedsWithUnreadRow struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	AuthorID        sql.NullInt64  `json:"author_id"`
	Title           string         `json:"title"`
	FeedUrl         string         `json:"feed_url"`
	HomeUrl         sql.NullString `json:"home_url"`
	Description     sql.NullString `json:"description"`
	Etag            sql.NullString `json:"etag"`
	LastModified    sql.NullString `json:"last_modified"`
	LastPolledAt    sql.NullString `json:"last_polled_at"`
	LastError       sql.NullString `json:"last_error"`
	PollIntervalSec int64          `json:"poll_interval_sec"`
	Enabled         bool           `json:"enabled"`
	CreatedAt       string         `json:"created_at"`
	AuthorName      sql.NullString `json:"author_name"`
	Unread          int64          `json:"unread"`
}

func (q *Queries) ListFeedsWithUnread(ctx context.Context, userID int64) ([]ListFeedsWithUnreadRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsWithUnread, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsWithUnreadRow
	for rows.Next() {
		var i ListFeedsWithUnreadRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorID,
			&i.Title,
			&i.FeedUrl,
			&i.HomeUrl,
			&i.Description,
			&i.Etag,
			&i.LastModified,
			&i.LastPolledAt,
			&i.LastError,
			&i.PollIntervalSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.AuthorName,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedEnabled = `-- name: SetFeedEnabled :exec
UPDATE feeds
SET enabled = ?
WHERE id = ? AND user_id = ?
`

type SetFeedEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) SetFeedEnabled(ctx context.Context, arg SetFeedEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setFeedEnabled, arg.Enabled, arg.ID, arg.UserID)
	return err
}

const setFeedPollMeta = `-- name: SetFeedPollMeta :exec
UPDATE feeds
SET etag = ?, last_modified = ?, last_polled_at = ?, last_error = ?
WHERE id = ?
`

type SetFeedPollMetaParams struct {
	Etag         sql.NullString `json:"etag"`
	LastModified sql.NullString `json:"last_modified"`
	LastPolledAt sql.NullString `json:"last_polled_at"`
	LastError    sql.NullString `json:"last_error"`
	ID           int64          `json:"id"`
}

func (q *Queries) SetFeedPollMeta(ctx context.Context, arg SetFeedPollMetaParams) error {
	_, err := q.db.ExecContext(ctx, setFeedPollMeta,
		arg.Etag,
		arg.LastModified,
		arg.LastPolledAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const updateFeed = `-- name: UpdateFeed :execresult
UPDATE feeds
SET author_id = ?, title = ?, feed_url = ?, home_url = ?, description = ?,
    poll_interval_sec = ?, enabled = ?
WHERE id = ? AND user_id = ?
`

type UpdateFeedParams struct {
	AuthorID        sql.NullInt64  `json:"author_id"`
	Title           string         `json:"title"`
	FeedUrl         string         `json:"feed_url"`
	HomeUrl         sql.NullString `json:"home_url"`
	Description     sql.NullString `json:"description"`
	PollIntervalSec int64          `json:"poll_interval_sec"`
	Enabled         bool           `json:"enabled"`
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFeed,
		arg.AuthorID,
		arg.Title,
		arg.FeedUrl,
		arg.HomeUrl,
		arg.Description,
		arg.PollIntervalSec,
		arg.Enabled,
		arg.ID,
		arg.UserID,
	)
}
