// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Author struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	Name          string         `json:"name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	AvatarKey     sql.NullString `json:"avatar_key"`
	LastFetchedAt sql.NullString `json:"last_fetched_at"`
	Description   sql.NullString `json:"description"`
	IsSystem      int64          `json:"is_system"`
	CreatedAt     string         `json:"created_at"`
}

type AuthorLink struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	AuthorID  int64          `json:"author_id"`
	Label     sql.NullString `json:"label"`
	Url       string         `json:"url"`
	CreatedAt string         `json:"created_at"`
}

type Collection struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
	IsAuto    int64  `json:"is_auto"`
	CreatedAt string `json:"created_at"`
}

type CollectionFeed struct {
	CollectionID int64 `json:"collection_id"`
	FeedID       int64 `json:"feed_id"`
}

type Feed struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	AuthorID         int64          `json:"author_id"`
	Title            string         `json:"title"`
	FeedUrl          string         `json:"feed_url"`
	HomeUrl          sql.NullString `json:"home_url"`
	Description      sql.NullString `json:"description"`
	Etag             sql.NullString `json:"etag"`
	LastModified     sql.NullString `json:"last_modified"`
	LastPolledAt     sql.NullString `json:"last_polled_at"`
	LastError        sql.NullString `json:"last_error"`
	NextPageUrl      string         `json:"next_page_url"`
	PollIntervalSec  int64          `json:"poll_interval_sec"`
	PollIntervalAuto int64          `json:"poll_interval_auto"`
	LastItemAt       sql.NullString `json:"last_item_at"`
	NextPollAt       sql.NullString `json:"next_poll_at"`
	PluginName       string         `json:"plugin_name"`
	DisabledReason   sql.NullString `json:"disabled_reason"`
	Enabled          bool           `json:"enabled"`
	IsSystem         int64          `json:"is_system"`
	Rank             int64          `json:"rank"`
	CacheImages      int64          `json:"cache_images"`
	CreatedAt        string         `json:"created_at"`
}

type Item struct {
	ID             int64          `json:"id"`
	FeedID         int64          `json:"feed_id"`
	UserID         int64          `json:"user_id"`
	Guid           string         `json:"guid"`
	DedupKey       string         `json:"dedup_key"`
	CrossKey       string         `json:"cross_key"`
	Title          string         `json:"title"`
	Link           string         `json:"link"`
	Summary        string         `json:"summary"`
	Content        string         `json:"content"`
	Categories     string         `json:"categories"`
	DurationSec    sql.NullInt64  `json:"duration_sec"`
	ImageUrl       sql.NullString `json:"image_url"`
	ImageCacheKey  sql.NullString `json:"image_cache_key"`
	ImageCacheSize int64          `json:"image_cache_size"`
	PublishedAt    sql.NullString `json:"published_at"`
	FetchedAt      string         `json:"fetched_at"`
	Read           bool           `json:"read"`
	ReadAt         sql.NullString `json:"read_at"`
	Favorite       bool           `json:"favorite"`
	Bookmark       bool           `json:"bookmark"`
}

type ItemCategory struct {
	ItemID   int64  `json:"item_id"`
	Category string `json:"category"`
}

type ItemEnclosure struct {
	ID        int64          `json:"id"`
	ItemID    int64          `json:"item_id"`
	Url       string         `json:"url"`
	Title     string         `json:"title"`
	MimeType  sql.NullString `json:"mime_type"`
	Size      int64          `json:"size"`
	Sort      int64          `json:"sort"`
	Kind      string         `json:"kind"`
	Poster    string         `json:"poster"`
	CacheKey  string         `json:"cache_key"`
	CacheSize int64          `json:"cache_size"`
}

type ItemFeed struct {
	ItemID    int64  `json:"item_id"`
	FeedID    int64  `json:"feed_id"`
	CreatedAt string `json:"created_at"`
}

type ItemsFt struct {
	Rowid   int64  `json:"rowid"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type List struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	ShareToken sql.NullString `json:"share_token"`
	CreatedAt  string         `json:"created_at"`
}

type ListItem struct {
	ListID    int64  `json:"list_id"`
	ItemID    int64  `json:"item_id"`
	CreatedAt string `json:"created_at"`
}

type Session struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SharedItem struct {
	ID        int64  `json:"id"`
	ItemID    int64  `json:"item_id"`
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
}

type SourceIcon struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	Domain        string         `json:"domain"`
	IconUrl       string         `json:"icon_url"`
	ContentType   sql.NullString `json:"content_type"`
	IconData      []byte         `json:"icon_data"`
	IconKey       sql.NullString `json:"icon_key"`
	LastFetchedAt sql.NullString `json:"last_fetched_at"`
	CreatedAt     string         `json:"created_at"`
}

type User struct {
	ID                    int64          `json:"id"`
	Username              string         `json:"username"`
	PasswordHash          string         `json:"password_hash"`
	IsAdmin               bool           `json:"is_admin"`
	SignupBannerDismissed bool           `json:"signup_banner_dismissed"`
	AvatarKey             sql.NullString `json:"avatar_key"`
	AvatarData            []byte         `json:"avatar_data"`
	AvatarContentType     sql.NullString `json:"avatar_content_type"`
	AvatarUrl             sql.NullString `json:"avatar_url"`
	Timezone              sql.NullString `json:"timezone"`
	Theme                 string         `json:"theme"`
	AccentColor           string         `json:"accent_color"`
	HomeConfig            sql.NullString `json:"home_config"`
	AutoReadAfterDays     int64          `json:"auto_read_after_days"`
	HideUnreadCounts      bool           `json:"hide_unread_counts"`
	HideUnreadNav         bool           `json:"hide_unread_nav"`
	GridMaxColumns        int64          `json:"grid_max_columns"`
	IsEphemeral           int64          `json:"is_ephemeral"`
	ExpiresAt             sql.NullString `json:"expires_at"`
	FavoritesShareToken   sql.NullString `json:"favorites_share_token"`
	BookmarksShareToken   sql.NullString `json:"bookmarks_share_token"`
	CreatedAt             string         `json:"created_at"`
}

type UserViewPref struct {
	UserID    int64  `json:"user_id"`
	Scope     string `json:"scope"`
	Mode      string `json:"mode"`
	UpdatedAt string `json:"updated_at"`
}
