baseURL = "https://nanoflux.app"
title = "nanoflux"
description = "A dead-simple, self-hosted RSS reader."
locale = "en"
enableRobotsTXT = true
summaryLength = 30
enableEmoji = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[pagination]
  pagerSize = 25

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/metruzanca/nanoflux"
  weight = 10