locale = "en"
label = "English"
weight = 1
title = "nanoflux"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "A dead-simple, self-hosted RSS reader."

[params.author]
  name = "nanoflux"
  headline = "Read the web, your way."
  bio = "A dead-simple, self-hosted RSS reader."
  links = [
    { github = "https://github.com/metruzanca/nanoflux" },
  ]